[package]
name = "pipe"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariadne = "0.1.3"
chumsky = { path = "../chumsky"}
indoc = "1.0.3"

[dev-dependencies]
pretty_assertions = "1.0.0"
